### PR TITLE
Add stream rewind support

### PR DESCRIPTION
**Pull request by david-kristin**
As of xml-string-streamer:0.13, it supports stream rewinding.

I implemented StreamInterface's isSeekable() and rewind() methods to ensure consistency between a file source and a Guzzle source.

Moreover, I added a PHPUnit dependency.

### CODE REVIEW

**Comment by prewk** [comment]
Thanks for contributing, it looks convincing enough for this old dog of a library!

**Comment by prewk** [comment]
Released as `0.4.0`

**Comment by david-kristin** [comment]
Thank you, Oskar. :+1: 

Maybe I'll contribute with even more PRs as my app heavily depends on xmlss.

**Comment by prewk** [comment]
Cool, I'm happy you've found good use for my lib :)

Here's a tip: a library which is a bit more modern that does similar things: https://github.com/TBPixel/xml-streamer

**Pull request merged**
